import { GoogleGenerativeAI } from '@google/generative-ai';

const apiKey = process.env.NEXT_PUBLIC_GEMINI_API_KEY || '';
const genAI = new GoogleGenerativeAI(apiKey);

export interface ProjectInfo {
  projectName: string;
  projectDescription: string;
  bio: string;
  clientInfo: string;
  keyMetrics?: {
    label: string;
    value: number;
  }[];
  additionalInfo?: string;
  uploadedElements?: {
    type: 'image' | 'video';
    file: string;
    title: string;
  }[];
}

export interface AIGeneratedElement {
  type: 'text' | 'svg' | 'image' | 'video';
  content: string;
  title: string;
  duration: number;
  start: number;
  animation: string;
  position: { x: number; y: number };
  color?: string; // Used for theme color in SVG generation
  svgContent?: string; // Complete SVG markup generated by Gemini
  file?: string; // Reference to uploaded media file (index)
}



export async function generateVideoElements(projectInfo: ProjectInfo) {
  try {
    const model = genAI.getGenerativeModel({ model: 'gemini-3-flash-preview' });

    const uploadedImagesInfo = projectInfo.uploadedElements && projectInfo.uploadedElements.length > 0
      ? `\n\nUser has uploaded ${projectInfo.uploadedElements.length} media file(s):\n${projectInfo.uploadedElements.map((el, i) => `${i + 1}. ${el.type}: "${el.title}"`).join('\n')}\n\nIMPORTANT: You MUST include ALL uploaded images/videos in the presentation. Reference them by their index number (0-${projectInfo.uploadedElements.length - 1}).`
      : '';

    const prompt = `You are a professional video presentation creator. Create a CONCISE, VISUAL-FOCUSED video presentation (MAX 30 SECONDS total duration).

Project Name: ${projectInfo.projectName}
Project Description: ${projectInfo.projectDescription}
Bio/About: ${projectInfo.bio}
Client Information: ${projectInfo.clientInfo}
${projectInfo.keyMetrics ? `Key Metrics: ${JSON.stringify(projectInfo.keyMetrics)}` : ''}
${projectInfo.additionalInfo || ''}${uploadedImagesInfo}

Create a video presentation with 6-10 elements (MAX 30 SECONDS TOTAL):

CRITICAL RULES:
1. MAX 30 SECONDS total duration
2. Text: MINIMAL, CONCISE, 3-5 WORDS MAX per text element
3. Prioritize: IMAGES/VIDEOS (60%) > GRAPHS (30%) > TEXT (10%)
4. ALL text MUST use HANDWRITING-STYLE SVG paths with strokeDashoffset animation
5. Font size equivalent: 24-48px stroke-width (3-6px)
6. If metrics provided, create ANIMATED graph SVGs
7. Include ALL uploaded media

Elements to create:
1. Title (3-5 words, SVG, 3s max)
2. ALL uploaded images/videos (4-5s each)
3. If metrics: Animated graph (5-6s)
4. Key feature (3-5 words, SVG, 3s)
5. Call to action (3-5 words, SVG, 3s)

For each element:
- type: "svg" (handwriting text/animated graphs), "image", or "video"
- content: ULTRA CONCISE text (3-5 words) or graph description
- title: element name
- duration: 2-6 seconds (total must not exceed 30s)
- start: when it starts (ensure total ≤ 30s)
- animation: fade, slideLeft, slideRight, slideUp, slideDown, zoomIn, zoomOut
- position: {x, y} (x: 20-200, y: 50-300 for visibility)
- color: USE CONSISTENT THEME - Pick ONE color family and use shades: Purple (#8263F4, #9B7EFF, #B49FFF) OR Blue (#3B82F6, #60A5FA, #93C5FD) OR Green (#10B981, #34D399, #6EE7B7)
- file: for image/video, index as string ("0", "1")
- svgContent: FOR ALL SVG ELEMENTS, generate COMPLETE SVG markup with handwriting animations for text

SVG GENERATION RULES (CRITICAL):
For ALL type="svg" elements, you MUST generate complete animated SVG code in the "svgContent" property.

=== TEXT SVG - HANDWRITING ANIMATION (REQUIRED) ===
For ALL text elements, use HANDWRITING ANIMATION with SVG paths and strokeDashoffset:
- Convert text to SVG <path> elements (not <text> tags)
- Use stroke-based rendering with strokeDashoffset animation
- Animate from full dashoffset to 0 to create drawing effect
- Use stroke color (theme color) with NO fill initially
- Add glow/shadow filters for beautiful effect

HANDWRITING PATH CREATION GUIDE:
- Create cursive/script-style letter paths using SVG path commands
- Use M (moveto), L (lineto), Q (quadratic curve), C (cubic curve)
- Connect letters naturally like handwriting - flowing, organic shapes
- Add natural variations - slight curves, varying heights
- strokeDasharray should be large (1000-2000) to cover entire path
- strokeDashoffset animates from same value to 0

HANDWRITING TEXT EXAMPLE (CRITICAL - USE THIS PATTERN):
"<svg width=\\"600\\" height=\\"120\\" xmlns=\\"http://www.w3.org/2000/svg\\" viewBox=\\"0 0 600 120\\"><defs><filter id=\\"glow\\"><feGaussianBlur stdDeviation=\\"3\\" result=\\"coloredBlur\\"/><feMerge><feMergeNode in=\\"coloredBlur\\"/><feMergeNode in=\\"SourceGraphic\\"/></feMerge></filter></defs><path d=\\"M50,60 Q80,20 120,60 T190,60 M210,30 L210,90 M230,60 Q260,20 300,60\\" fill=\\"none\\" stroke=\\"#8263F4\\" stroke-width=\\"4\\" stroke-linecap=\\"round\\" stroke-linejoin=\\"round\\" filter=\\"url(#glow)\\" stroke-dasharray=\\"1000\\" stroke-dashoffset=\\"1000\\"><animate attributeName=\\"stroke-dashoffset\\" from=\\"1000\\" to=\\"0\\" dur=\\"2s\\" fill=\\"freeze\\"/></path></svg>"

IMPORTANT: 
- Each word/letter should be a continuous path with curves
- Use stroke-dasharray and stroke-dashoffset for handwriting reveal
- Make paths look like handwritten calligraphy/script
- Keep stroke-width between 3-6 for readability
- Use smooth curves (Q, C commands) for organic handwritten feel
- Duration should be 1.5-3s for smooth handwriting animation

=== GRAPH/CHART SVG EXAMPLES ===
For graphs (when metrics provided), generate ANIMATED CHARTS:

BAR CHART EXAMPLE:
"<svg width=\\"600\\" height=\\"400\\" xmlns=\\"http://www.w3.org/2000/svg\\"><text x=\\"300\\" y=\\"30\\" font-size=\\"24\\" font-weight=\\"bold\\" text-anchor=\\"middle\\" fill=\\"#1a1a1a\\">Revenue Growth</text><rect x=\\"80\\" y=\\"340\\" width=\\"80\\" height=\\"200\\" fill=\\"#8263F4\\" rx=\\"4\\"><animate attributeName=\\"y\\" from=\\"340\\" to=\\"140\\" dur=\\"1s\\" fill=\\"freeze\\"/><animate attributeName=\\"height\\" from=\\"0\\" to=\\"200\\" dur=\\"1s\\" fill=\\"freeze\\"/></rect><text x=\\"120\\" y=\\"360\\" font-size=\\"14\\" text-anchor=\\"middle\\" fill=\\"#666\\">Q1</text><rect x=\\"200\\" y=\\"340\\" width=\\"80\\" height=\\"150\\" fill=\\"#9B7EFF\\" rx=\\"4\\"><animate attributeName=\\"y\\" from=\\"340\\" to=\\"190\\" dur=\\"1s\\" fill=\\"freeze\\" begin=\\"0.2s\\"/><animate attributeName=\\"height\\" from=\\"0\\" to=\\"150\\" dur=\\"1s\\" fill=\\"freeze\\" begin=\\"0.2s\\"/></rect><text x=\\"240\\" y=\\"360\\" font-size=\\"14\\" text-anchor=\\"middle\\" fill=\\"#666\\">Q2</text></svg>"

LINE CHART EXAMPLE:
"<svg width=\\"600\\" height=\\"400\\" xmlns=\\"http://www.w3.org/2000/svg\\"><defs><linearGradient id=\\"lineGrad\\" x1=\\"0%\\" y1=\\"0%\\" x2=\\"100%\\" y2=\\"0%\\"><stop offset=\\"0%\\" style=\\"stop-color:#8263F4\\"/><stop offset=\\"100%\\" style=\\"stop-color:#B8A3FF\\"/></linearGradient></defs><text x=\\"300\\" y=\\"30\\" font-size=\\"24\\" font-weight=\\"bold\\" text-anchor=\\"middle\\" fill=\\"#1a1a1a\\">User Growth</text><path d=\\"M 60 340 L 180 280 L 300 200 L 420 160 L 540 100\\" fill=\\"none\\" stroke=\\"url(#lineGrad)\\" stroke-width=\\"4\\" stroke-linecap=\\"round\\"><animate attributeName=\\"stroke-dasharray\\" from=\\"0,1000\\" to=\\"1000,0\\" dur=\\"2s\\" fill=\\"freeze\\"/></path><circle cx=\\"60\\" cy=\\"340\\" r=\\"6\\" fill=\\"#8263F4\\"><animate attributeName=\\"r\\" from=\\"0\\" to=\\"6\\" dur=\\"0.5s\\" fill=\\"freeze\\" begin=\\"1.5s\\"/></circle></svg>"

ANIMATION CONSISTENCY: Use similar SVG filter styles for all text elements.
THEME CONSISTENCY: Use ONE color family (purple OR blue OR green shades only).

Return ONLY a valid JSON array. EXAMPLE:
[
  {
    "type": "svg",
    "content": "Product Launch",
    "title": "Title",
    "duration": 3,
    "start": 0,
    "animation": "fade",
    "position": {"x": 50, "y": 120},
    "color": "#8263F4",
    "svgContent": "<svg width=\\"600\\" height=\\"120\\" xmlns=\\"http://www.w3.org/2000/svg\\" viewBox=\\"0 0 600 120\\"><defs><filter id=\\"glow1\\"><feGaussianBlur stdDeviation=\\"3\\" result=\\"blur\\"/><feMerge><feMergeNode in=\\"blur\\"/><feMergeNode in=\\"SourceGraphic\\"/></feMerge></filter></defs><path d=\\"M40,60 Q50,30 70,50 Q90,70 110,50 Q130,30 150,60 M170,40 L170,80 M170,40 Q190,35 210,50 Q230,65 210,80\\" fill=\\"none\\" stroke=\\"#8263F4\\" stroke-width=\\"5\\" stroke-linecap=\\"round\\" stroke-linejoin=\\"round\\" filter=\\"url(#glow1)\\" stroke-dasharray=\\"1000\\" stroke-dashoffset=\\"1000\\"><animate attributeName=\\"stroke-dashoffset\\" from=\\"1000\\" to=\\"0\\" dur=\\"2s\\" fill=\\"freeze\\"/></path></svg>"
  },
  {
    "type": "image",
    "content": "Product",
    "title": "Image 1",
    "duration": 5,
    "start": 3,
    "animation": "fade",
    "position": {"x": 0, "y": 0},
    "file": "0"
  },
  {
    "type": "svg",
    "content": "Revenue Growth",
    "title": "Bar Chart",
    "duration": 6,
    "start": 8,
    "animation": "slideUp",
    "position": {"x": 50, "y": 100},
    "color": "#9B7EFF",
    "svgContent": "<svg width=\\"600\\" height=\\"400\\" xmlns=\\"http://www.w3.org/2000/svg\\"><text x=\\"300\\" y=\\"30\\" font-size=\\"24\\" font-weight=\\"bold\\" text-anchor=\\"middle\\" fill=\\"#1a1a1a\\">Revenue</text><rect x=\\"80\\" y=\\"340\\" width=\\"80\\" height=\\"200\\" fill=\\"#8263F4\\" rx=\\"4\\"><animate attributeName=\\"y\\" from=\\"340\\" to=\\"140\\" dur=\\"1s\\" fill=\\"freeze\\"/><animate attributeName=\\"height\\" from=\\"0\\" to=\\"200\\" dur=\\"1s\\" fill=\\"freeze\\"/></rect></svg>"
  }
]

KEY: Keep total duration ≤ 30s, text ≤ 5 words, ALL TEXT MUST USE HANDWRITING SVG PATHS with strokeDashoffset animation, ONE color theme.`;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();
    
    // Extract JSON from response (handle markdown code blocks)
    let jsonText = text.trim();
    if (jsonText.startsWith('```json')) {
      jsonText = jsonText.replace(/```json\n?/g, '').replace(/```\n?$/g, '');
    } else if (jsonText.startsWith('```')) {
      jsonText = jsonText.replace(/```\n?/g, '').replace(/```\n?$/g, '');
    }
    
    const elements: AIGeneratedElement[] = JSON.parse(jsonText);
    return elements;
  } catch (error) {
    console.error('Error generating video elements:', error);
    throw error;
  }
}
